### ISSUE TITLE
object-curly-newline

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#100]
http://eslint.org/docs/rules/object-curly-newline

`["error", { "minProperties": 2 }]`

need two properties at least to start multilining

- - -

#251 updated the rule to:

```js
'object-curly-newline': [2, { multiline: true }]
```
(_scroll down for discussion/reasoning/examples_)

**Comment by eliascodes** [comment]
To clarify, this config will still allow multilining for objects with less that two keys, but disallows single-lining objects with more than two keys.

**Comment by shouston3** [comment]
I'm finding this one a little annoying, for example:

```
var obj = { key: function (arg) {
  return 'string';
}}
```

We have to have the key and value on the same line as the object bracket, I would prefer this:

```
var obj = {
  key: function (arg) {
    return 'string';
  }
};
```

Also, if we have to have two small keys and values they must be on seperate lines:

```
var obj = {
  k: 'v',
  k2: 'v2
}
```

I think we should enforce new lines for more than 1 key, but we should not enforce same lines for an object with one key

**Comment by eliascodes** [comment]
I think this
```javascript
var array = [
  { a: 1, b: 2 },
  { a: 2, b: 4 },
  { a: 0, b: 5 },
  { a: 9, b: 4 },
]
```

is much cleaner than what the current linter settings enforce, which is this:

```javscript
var array = [
  {
    a: 1, b: 2 
  },
  { 
    a: 2, b: 4 
  },
  { 
    a: 0, b: 5 
  },
  { 
    a: 9, b: 4 
  },
]
```

**Comment by des-des** [comment]
You want both?
`const smallObj = { outer: { inner: value } }`
```js
const bigObj = {
  a: 1,
  b: 2,
  c: 3,
  d: 'a quite long string',
  e: { this: is : { nested } }
  ['someMoreStuff to make this obj > 100 character']: 'bla bla bla'
}
```

**Comment by des-des** [comment]
ops

**Comment by nelsonic** [comment]
Latest version on NPM `v1.1.0` reflects the changes. 👍 
(_thanks @jrans_)
