### ISSUE TITLE
no-underscore-dangle

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#103]
http://eslint.org/docs/rules/no-underscore-dangle

"off"

this rule just addresses a naming convention that is used when exposing attributes that arent intended for consumption, but doesnt actually address the underlying issue.

**Comment by nelsonic** [comment]
if no-one has `strong` feelings about this, happy to have it `"off"` by default. (_agree it's style..._)
But is there a _reason_ for the _rule_ in the first place...?

http://stackoverflow.com/questions/4484424/underscore-prefix-for-property-and-method-names-in-javascript

I don't plan to use "classes" in my code, so don't _expect_ to have underscore dangle ... but not _against_ it. 👍
