### ISSUE TITLE
no-trailing-spaces

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#104]
http://eslint.org/docs/rules/no-trailing-spaces

"error"

**Comment by nelsonic** [comment]
@jrans does this mean we cannot have a space at the end of a line that has an in-line comment ?

**Comment by SimonLab** [comment]
An example of the rule with inline comment (not trailing space after the comment):
```
var myVar = 3;            // this inline code follow the rule but it can't have trailing spaces after this comment
```
