### ISSUE TITLE
no-self-compare

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#106]
http://eslint.org/docs/rules/no-self-compare

```
no-self-compare: 2
```

not very useful code:

```
if (x === x){
 // do something
}
```

**Comment by jrans** [comment]
typeof x === 'number' && isNaN(x) can be used instead of comparing NaN to itself

**Comment by nelsonic** [comment]
@SimonLab agree. can't think of a _practical_ use for this.
