### ISSUE TITLE
no-throw-literal

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#108]
http://eslint.org/docs/rules/no-throw-literal

Do we want to only throw Error objects?

#### Update
```
no-throw-literal: "error"
```

**Comment by jrans** [comment]
rule makes sense to me, @shouston3, @eliascodes ? Thoughts

**Comment by eliascodes** [comment]
I agree, always throw `Error` objects, so you get the stack trace.

**Comment by shouston3** [comment]
I think so

**Comment by nelsonic** [comment]
Didn't comment at the time, but agree. 😉 
Context: 

![hapi-auth-github-goodparts-no-throw-literal](https://cloud.githubusercontent.com/assets/194400/19223809/b1c5bac8-8e70-11e6-8387-77614863d140.png)
