### ISSUE TITLE
callback-return

### ISSUE THREAD

**Issue by eliascodes** [dwyl/goodparts#112]
http://eslint.org/docs/rules/callback-return

Should definitely return callbacks, but this rule only looks at predefined function names, so does not offer full protection. 

Would be worth deciding on a convention for callback names, and adding those to the list of calback names

```
["error", ["done", "next", "callback", "cb"]]
```

**Comment by nelsonic** [comment]
@eliascodes agreed, what do you _propose_ for callback name?
_short_ `cb` or _verbose_ `callback` ?
