### ISSUE TITLE
no-restricted-globals

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#154]
http://eslint.org/docs/rules/no-restricted-globals

It's unlikely that we name variable with the same name as a global variable but we can still use this rule if we need to.

**Comment by shouston3** [comment]
So what config option are we choosing for this?

I'm putting:

```
no-restricted-globals: "off"
```

For now

**Comment by nelsonic** [comment]
@shouston3 is there any _downside_ to restricting the re-definition of these `globals` ...?
so, the hard part here is _defining_ the globals that we don't want people to use ...
so for now, we can leave it `"off"` ...
