### ISSUE TITLE
no-sequences

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#163]
http://eslint.org/docs/rules/no-sequences

This is some of the worst syntax I've seen:
```
var a = (3, 5); // a = 5
```

The comma operator includes multiple expressions where only one is expected

```
no-sequences: 2
```

**Comment by eliascodes** [comment]
FYI your example is actually allowed under this rule:

From [here](http://eslint.org/docs/rules/no-sequences)
> This rule forbids the use of the comma operator, with the following exceptions:
    * In the initialization or update portions of a for statement.
    * If the expression sequence is explicitly wrapped in parentheses.

Ideally we wouldn't allow parenthesised sequences either, but seems like that would need a custom rule.
