### ISSUE TITLE
newline-before-return

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#169]
http://eslint.org/docs/rules/newline-before-return

`"2"` 

lets be clear when we're finsihed

**Comment by nelsonic** [comment]
@jrans I'm _uncertain_ what the setting is here. do we _want to enforce_ a newline before return?

**Comment by jrans** [comment]
@nelsonic is this too far? Just enforces that one more line of space and may be nice to keep that consistency in layout across our developers code. Happy to turn off though?

**Comment by shouston3** [comment]
I think we should trial enforcing a new line before a return and then review it after a week or so
