### ISSUE TITLE
new-parens

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#171]
http://eslint.org/docs/rules/new-parens

`"2"`

>> some coders believe that omitting the parentheses is inconsistent with the rest of the language and thus makes code less clear

we want conformity so choosing one or the other is good

**Comment by nelsonic** [comment]
We should get a _good example_ of where using the `new` keyword is a _good idea_.
until then, using `new` is to be _discouraged_ in our code.  
https://www.youtube.com/watch?v=ya4UHuXNygM&t=50m23s

**Comment by jrans** [comment]
@nelsonic ok but when we are using other modules and it is needed then this rule should apply

**Comment by eliascodes** [comment]
@nelsonic
```javascript
var Hapi = require('hapi');
var server = new Hapi.Server();
```
Although agree that we should void writing code ourselves that requires `new`
