### ISSUE TITLE
no-with

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#181]
http://eslint.org/docs/rules/no-with

"Use of the with statement is not recommended, as it may be the source of confusing bugs and compatibility issues" from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with)

We shouldn't be using `with` syntax, so

```
no-with: 2
```

**Comment by nelsonic** [comment]
pure confusion. 😕 
(_thanks for disabling  this_)
