### ISSUE TITLE
yoda

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#183]
http://eslint.org/docs/rules/yoda

This rule ensures that the variable is checked against the literal value and not the other way around:

correct
```
if (color === "red") {
    // ...
}
```

incorrect
```
if ("red" === color) {
    // ...
}
```

Also `exceptRange: true` allows:
```
if (x < -1 || 1 < x) {
    // ...
}
```
So,

```
yoda: [2, "never", { "exceptRange": true }]
```

**Comment by nelsonic** [comment]
@shouston3 this is more of a _style_ thing because the comparison is valid either way. But I _agree_ this is cleaner. `yoda` #FTW 🎉
