### ISSUE TITLE
jsx-quotes

### ISSUE THREAD

**Issue by eliascodes** [dwyl/goodparts#199]
eslint.org/docs/rules/jsx-quotes

```
jsx-quotes: "off"
```

jsx isnt part of the [standard dwyl stack](https://github.com/dwyl/technology-stack), so this is N/A

**Comment by nelsonic** [comment]
@eliascodes I'm up for using `JSX` when W3C make it a _standard_ ... 😉 
having XML-like code wrapped in a `render()` method nested in a `class` makes a _lot_ of sense. 👍

**Comment by eliascodes** [comment]
@nelsonic cool, lets revisit this then!
