### ISSUE TITLE
Installed goodparts from npm and got .eslintrc.js which requires './rules ...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/goodparts#248]
Hi @eliascodes / @shouston3 / @SimonLab / @jrans 
Hope your evening is going well...
I just tried to `npm install goodparts` and it creates an `.eslintrc.js` file in the root of my project:
![eslintrc-js-requires-rules](https://cloud.githubusercontent.com/assets/194400/18929116/ffcbffe8-85ba-11e6-8904-211e2611b0f4.png)
Which attempts to `require('./rules')` ... is this the _desired_ behaviour...?

**Comment by eliascodes** [comment]
@nelsonic see #247 and https://github.com/dwyl/abase/pull/46

This is our SHORT TERM HACK so we can use goodparts with atom. The file your seeing is just a symlink. The `./rules` file it's requiring is relative to the `goodparts` directory in node_modules, not the project root.

**Comment by nelsonic** [comment]
@eliascodes so it's ok to include this file in my `.gitignore` ?

**Comment by eliascodes** [comment]
@nelsonic yes I would recommend that you do.

**Comment by jrans** [comment]
@nelsonic @eliascodes symlinking isn't ideal. Just committed my `.eslintrc.js` symlink into my new repo and not too pleased. Obviously my bad but if I'm going to the effort of adding it to my .gitignore i'd rather just create an my own `.eslintrc.js` and extend the goodparts module saving having to use global eslint (in atom) which is again causing me problems working on other projects which have their own .eslintrc

**Comment by eliascodes** [comment]
@jrans what do you think about this:
* Remove the post-install script from goodparts `package.json`
* Default usage would then be to create a `.eslintrc` file which has `extends: goodparts`
* Add functionality to the `goodparts` CLI to do the symlinking if that's still something we want to keep (e.g. you would run `goodparts link` or something like that)

**Comment by eliascodes** [comment]
@jrans @nelsonic there is a problem with the approach I outlined above: any shareable configs must have package names of the form `"eslint-config-packageName"`. This is [documented here](http://eslint.org/docs/developer-guide/shareable-configs#creating-a-shareable-config), and you can see the [code that I think corresponds to it here](https://github.com/eslint/eslint/blob/660e0918933e6e7fede26bc675a0763a6b357c94/lib/config/config-initializer.js#L69-L71). I've tried it out locally and get an error thrown when eslint can't find the config. In my `.eslintrc.json`:
```json
{
  "extends": "goodparts"
}
```
Then when I try to run the `goodparts` CLI, I get:
```
Error: Cannot find module 'eslint-config-goodparts'
```

So a npm package by the name of `goodparts` cannot be used as a shareable config.

I've [pushed a branch](https://github.com/dwyl/goodparts/tree/issue-248) where I've implemented steps 1 and 3 from my last comment. Let me know if you want me to PR it.

**Comment by nelsonic** [comment]
@eliascodes _ideally_ we would _not_ have an `.eslintrc` or `.eslintrc.json` in _any_ of our projects and simply use the `goodparts` `.bin` script e.g: `npm run goodparts` ...

**Comment by eliascodes** [comment]
@nelsonic well happily that's already possible 😄

I can see why it is handy to have a real-time linter running in your editor though. If we do want to make that happen, it might just be better to bite the bullet and actually write an atom plugin at some point.

Anyway, please let me know if you would like me to submit a PR. If so, I need to write a couple more tests because I introduced a couple branches into the `bin/cmd.js` that aren't covered by a simple `require`.

**Comment by eliascodes** [comment]
Has this issue now been fully addressed (can it be closed)?

**Comment by nelsonic** [comment]
@eliascodes great question. we will know _soon_ ... https://github.com/dwyl/hapi-auth-jwt2/issues/211 😉

**Comment by nelsonic** [comment]
![hapi-auth-jwt2-no-eslintirc-file](https://cloud.githubusercontent.com/assets/194400/20477290/da51197e-afcc-11e6-9c6c-f7b10c91e940.png)

`#Succcess` ✅ 
Thanks @eliascodes ❤️
