### ISSUE TITLE
add instructions for how to display a goodparts badge (for all our projects!)

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#253]
It would be a nice addition to have a goodparts badge which you could place at the top of your readme.

**Comment by nelsonic** [comment]
[![JavaScript Style Guide](https://img.shields.io/badge/code%20style-goodparts-brightgreen.svg)](https://github.com/dwyl/goodparts)

**Comment by nelsonic** [comment]
@shouston3 is there a _better_ badge we can create...? :thinking:

**Comment by shouston3** [comment]
Forgot to close, sorry

**Comment by nelsonic** [comment]
@shouston3 no need to _apoligize_... thankyou for reminding us to create a badge. we should add _instructions_ for including the badge to https://github.com/dwyl/repo-badges ...
