### ISSUE TITLE
Error doesn't fail the pre commit hook

### ISSUE THREAD

**Issue by JMurphyWeb** [dwyl/goodparts#268]
Using module pre-commit, the `"lint": "path/to/files"` script, and the `"pre-commit": ["lint"]` added to our package.json, I can commit a file that fails the linting check. 

The error is printed to the console, but the file is still committed.

Perhaps some documentation/example of a pre commit hook in action if you have one?

**Comment by SimonLab** [comment]
@JMurphyWeb I think it's a duplicate now see #266 and it is now resolved (thanks @eliascodes ) with this PR #267

**Comment by JMurphyWeb** [comment]
Fair dos. Could add a little line to the readme.. I am happy to do this when I have it working.

**Comment by nelsonic** [comment]
@JMurphyWeb thanks for reporting this! (_and thanks @eliascodes for fixing it!_) ❤️  ✅ 
Please confirm it's working as expected then close the issue. 👍

**Comment by JMurphyWeb** [comment]
Seems to be working. I will make PR with README addition.
