### ISSUE TITLE
How do you *know* that Code written using "Good Parts" works everywhere?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/goodparts#272]
One of the questions that comes to mind when I'm reading the `README.md` is:

> How do you ***`know`*** that Code written using "Good Parts" ***works everywhere***....?

All the code in JavaScript the "Good Parts" was conforms to the **ECMAScript 3** spec.
This version of JavaScript was made a *standard* in ***December 1999*** it is _implemented_ by all browsers including **Internet Explorer 6**. 

By using this "_older_" (_but still perfectly functional_) subset of the language you can be **100% certain** that your code will work in _every_ web browser released this century. 

Only someone running **Windows 98** with [Internet Explorer 5](https://en.wikipedia.org/wiki/Internet_Explorer_5) will not be able to run your code ... don't laugh, there are people that still have this configuration especially in some "developing" countries/governments: https://www.quora.com/Why-would-someone-still-run-Windows-95-98-in-the-2010s-and-later but you can _safely_ ignore these people/users; they are _not_ (_never will be_) your customers. 😉

**Comment by Fl4m3Ph03n1x** [comment]
Don't mind my intrusion, but I fail to see what is your question. 

Also, DC recent talks expand the goodparts way beyond and into the realm of ECMA5. Not using classes, new and using factory functions are only some of the additions to his opinion.

**Comment by nelsonic** [comment]
@Fl4m3Ph03n1x thanks for reminding us that this issue is (_was_) still open. 👍 
We aren't writing and `new` JS on the front-end anymore; see: https://github.com/dwyl/learn-elm

**Comment by Fl4m3Ph03n1x** [comment]
@nelsonic thank you for your reply. Does it mean that this project is now over, or discontinued? I personally like the badge and I support its meaning.

**Comment by nelsonic** [comment]
@Fl4m3Ph03n1x not "over" or "discontinued".
We still have _several_ JS projects that use this Linter.
"Under-the-Hood" it uses `eslint` which is _good_
but is a bit of a "***moving target***" ... see: https://github.com/dwyl/goodparts/issues/281

If anyone had _time_ to address this issue I would be _delighted_!!

**Comment by Fl4m3Ph03n1x** [comment]
Looks like you fixed it. I left a comment there to be sure. Regarding this specific topic is there any assistance required?
