### ISSUE TITLE
require-await

### ISSUE THREAD

**Issue by nelsonic** [dwyl/goodparts#277]
https://travis-ci.org/dwyl/goodparts/builds/180930218#L698

![require-await-error](https://cloud.githubusercontent.com/assets/194400/20859034/5c74d490-b94b-11e6-94b3-43c8a6e3a2f4.png)

http://eslint.org/docs/rules/require-await

**Comment by iteles** [comment]
Implemented. Can this be closed?

**Comment by nelsonic** [comment]
@iteles it's only "_implemented_" in that it's set to `"off"` given that we aren't using `async` ... but yeah, we can close the issue. 👍
