### ISSUE TITLE
capitalized-comments

### ISSUE THREAD

**Issue by nelsonic** [dwyl/goodparts#278]
see: http://eslint.org/docs/rules/capitalized-comments
I don't see an _advantage_ to "_enforcing_" this rule.

**Comment by ryanpcmcquen** [comment]
Crockford himself writes comments in complete sentences:

![screenshot 2016-12-03 at 06 56 51](https://cloud.githubusercontent.com/assets/772937/20860131/b53189f0-b925-11e6-9f5a-474043d7ddc0.png)

https://github.com/douglascrockford/JSLint/blob/master/jslint.js#L129

**Comment by nelsonic** [comment]
@ryanpcmcquen I'm a _fan_ of comments as _complete human-readable sentences_ but if my linter told me I had to capitalise the start of a comment I don't think I would feel 😍  ...

**Comment by iteles** [comment]
I think the consistency needs to be in the quality of the comments (i.e. they need to make sense to a beginner and include complete information as well as *exist* in the first place) - if we crack that, the capitalisation is the least of our problems.
