### ISSUE TITLE
no-empty

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#28]
http://eslint.org/docs/rules/no-empty

There should be no empty if, while, switch, try statements

```
no-empty: [2, "never"]
```

**Comment by nelsonic** [comment]
can't think of a situation where having an empty block statement would be _useful_... 👍

**Comment by jedwards1211** [comment]
Occasionally one needs a noop catch block just to suppress errors.  Call it a code smell, but sometimes it's the only thing to do -- for instance in my PRs to `terminate`, I had to suppress errors from killing child processes.

**Comment by jedwards1211** [comment]
but one can put a comment in the empty block anyway, so not a huge deal
