### ISSUE TITLE
GPL 2.0 license

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [dwyl/goodparts#282]
I am using https://www.versioneye.com to check dependencies and licenses. 

I have noticed that this project uses GPL 2.0, which means that if I am working for a company and I want to use a library that makes use of this module, not only can't I do it, I can't also use any NPM modules using it, because according to my understanding, the GPL 2.0 license is transitive and it forces all software containing at least 1 module with it to be open sourced.

I personally believe this is not very good. I would love to use this in my work but as you may guess my company surely wouldn't be happy to open source everything. 

Is there a way to have another license? I really like the "goodparts" badge, but if it means no one can use my libraries (my company included), than I would rather remove it and no use this linter at all.

And like me many other people are bound to think the same.

Any opinions?

**Comment by nelsonic** [comment]
@Fl4m3Ph03n1x which license _are_ you using in your company?
(_we have a `<strong>preference</strong>` for GPL v.2 because it encourages Open Source as opposed to forking and closing ..._)

**Comment by Fl4m3Ph03n1x** [comment]
I understand that, but since the license is transitive, it pretty much means, for example, that none of the libraries I write can be used by my company. 

Which kind defeats the whole purpose of the thing. I want to write libraries that are open source in order to benefit both my company and me, but with this license I **simply can't**. 

This "free or death" clause literally means that and works as an ultimatum. 

Since I want to help the open source world writing open source libraries while still benefiting my company, the only choice I have left is to not use jslint and to not promote the project nor its badge. 

It is a shame, since I truly believed in the same ideals the project does.

**Comment by matjack1** [comment]
From my point of view, seen the kind of project that goodparts is, you shouldn't have any problem using it in another project which is not GPL licensed, as I think this is a case of "mere aggregation" https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#MereAggregation

On the other side, if you plan to write some software starting from goodparts, or on top of it, the yes, you should licence it as GPLv2 (or v3).

Hope it helps.

**Comment by Fl4m3Ph03n1x** [comment]
I see. Since my libraries would work regardless of jslint, and the programs and projects where I use them would work independently, then I believe it is in fact a case of **mere aggregation**. 

Since I am not writing an  application that is built on top or expands jslint, it means I can use it in all my libraries and benefit everyone at the same time. 

A win win situation. 

Thanks for the explanation!

**Comment by nelsonic** [comment]
@matjack1 thanks _very_ much for sharing the link to MereAggregation 🎉
