### ISSUE TITLE
Istanbul is deprecated, migrate to NYC

### ISSUE THREAD

**Issue by oleg-koval** [dwyl/goodparts#286]
During `npm install` i receive this:

```
This module is no longer maintained, try this instead: npm i nyc Visit https://istanbul.js.org/integrations for other alternatives.
```

Also package-lock.json is missing.

I already have a branch with following migration, if its needed I can open a PR

**Comment by nelsonic** [comment]
Hi @oleg-koval thank you for opening this issue! 
If you have already done the work, please PR the change from istanbul to nyc 👍 
(_we are aware of it and it's on our list of things to update:_ https://github.com/dwyl/learn-istanbul/issues/20 ...)
Our reasoning for leaving the `package-lock.json` file out of version control is that it creates a lot of noise whenever something is updated (_without much benefit to the users_) ...

**Comment by oleg-koval** [comment]
@nelsonic I understand your concern about package-lock
