### ISSUE TITLE
space-infix-ops

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#32]
http://eslint.org/docs/rules/space-infix-ops

`2, {"int32Hint": false}]`

readability reasons but allowing for `bar|0`

**Comment by nelsonic** [comment]
@jrans I _personally_ prefer to _enforce_ space around infix operators for readability.
when is `bar|0` _useful_ ...? (_code example please if possible_..._)

**Comment by shouston3** [comment]
@jrans `2, {"int32Hint": false}` doesn't allow `bar|0` with no spaces

@nelsonic Despite never using this operator, I'd like to have `bar | 0`

**Comment by jrans** [comment]
@shouston whoops, and @nelsonic I guess i was treating it more like a unary operator as the focus is on the bar but since I don't use it I'm happy to go with you guys 👍
