### ISSUE TITLE
space-before-function-paren

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#36]
http://eslint.org/docs/rules/space-before-function-paren

`[2, { "anonymous": "always", "named": "always" }]`

**Comment by eliascodes** [comment]
From [here](http://jslint.com/help.html)

> Spaces are used to make things that are not invocations look less like invocations.

**Comment by nelsonic** [comment]
I _prefer_ it this way. glad DC does too, cause I don't have a "logical" reason for it... 😉
