### ISSUE TITLE
require-jsdoc

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#51]
http://eslint.org/docs/rules/require-jsdoc

```
["error", {
  "require": {
    "FunctionDeclaration": false,
    "MethodDefinition": false,
    "ClassDeclaration": false
  }
}]
```

Should be a per project decision

**Comment by nelsonic** [comment]
@jrans is there a _down side_ to _requiring_ JSDoc style comments in a project...?

**Comment by eliascodes** [comment]
So I'm changing this to `"off"` instead of whats specified, because there's no point having the rule error, but disabling it for `FunctionDeclaration`, `MethodDefinition` and `ClassDeclaration` nodes.
