### ISSUE TITLE
quotes

### ISSUE THREAD

**Issue by eliascodes** [dwyl/goodparts#53]
http://eslint.org/docs/rules/quotes

Single quotes because:
* no shift key required
* easier to context switch between JS and HTML (as long as you use double quotes in your HTML)

Do not allow template literals because they are an ES6 feature.
Prefer use of escape characters instead of having inconsistent quoting style.

```
"quotes": [2, "single", {"avoidEscape": false, "allowTemplateLiterals": false}]
```

**Comment by iteles** [comment]
The 'double quotes in HTML' will need to go into our style guide separately 👍 

Also, linked to https://github.com/dwyl/style-guide#quotes

**Comment by nelsonic** [comment]
@eliascodes agree with using _single quotes_ for strings. 👍 
I think template literals should be discussed in a _separate_ issue...

**Comment by tunnckoCore** [comment]
please :D don't add `no-template-curly` in normal strings, like standard@8 did recently :D 

for things like

```js
var str = 'foo ${bar} baz' /* eslint-disable-line no-template-curly-in-string */
```

**Comment by Fl4m3Ph03n1x** [comment]
Totally late to the party but I would like to suggest we remove double quotes as an error and, perhaps add it only as a warning.

Reason:
1 - For some European keyboards you still need to press shift to type  the single quote character (https://stackoverflow.com/questions/9959928/double-quotes-vs-single-quotes-in-javascript), eg, the German typical keyboard.
2 - Context switching is easier when both HTML and JS use the same convention. Everyone I know uses double quotes for everything, for example. 
3 - Using double quotes makes context switching easier to JSON, which does require double quotes afaik.
4 - Template literals use the ` character, not the single quote one. I really don't see the advantage/disadvantage of single or double quotes
5 - when writing test stories in English (for TDD), double quotes makes it possible to write a test name where words like "don't" or "it's" are possible. 

Opinions ?

**Comment by nelsonic** [comment]
@Fl4m3Ph03n1x while I _agree_ that this _could_ be a warning instead of an error,
warnings get _very_ noisy, it's simpler to have them as "errors" because then _everyone_ knows not to "_pollute_" the log with warnings. 👍

**Comment by 92arpitgoyal** [comment]
I have a bit general question, I use prettier and eslint till now for linting and don't want to remove them. Can we add a basic config to docs?(for eslint or prettier to follow goodparts)

**Comment by nelsonic** [comment]
@92arpitgoyal that would be a _great_ idea. 🥇

**Comment by nelsonic** [comment]
@92arpitgoyal that would be a good starting point.
please consider opening a _new_ issue to discuss further (_rather than commenting on a closed one_)
thanks!
