### ISSUE TITLE
valid-jsdoc

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#56]
http://eslint.org/docs/rules/valid-jsdoc

Prefer:

returns over return,
param over params, arg or args

```
valid-jsdoc: [2, ["prefer": { "arg": "param", "argument": "param", "return": "returns" }]
```

**Comment by nelsonic** [comment]
@shouston3 we don't really have a _use_ for `abstract` / `virtual` ... see: http://usejsdoc.org/tags-abstract.html just leave it _out_ for now. 👍

**Comment by nelsonic** [comment]
i just came up against this one where the JSDOC I was writing _looked_ fine but ESLint was reporting a `syntax error in jsdoc` without _any_ further info ... 
I ended up copy-pasting the JSDOC block from http://eslint.org/docs/rules/valid-jsdoc and then updating it to my needs, but it wasn't a _pleasant_ experience ... :thinking:

**Comment by SimonLab** [comment]
Do you still have the example of your jsdoc maybe we can spot if there was an error? it might also be just a bug of the rules. There is also the "returns" keyword with the "s", I made a few errors with this one.
