### ISSUE TITLE
class-methods-use-this

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#58]
http://eslint.org/docs/rules/class-methods-use-this

NA: We won't use classes so we don't want to include this rule

**Comment by jrans** [comment]
@SimonLab Surely this rule therefore should be turned on as would only encourage not to use classes. If forever reason classes were allowed at a later stage we would be in a position to discourage unnecessary creations.

**Comment by nelsonic** [comment]
https://github.com/joshburgess/not-awesome-es6-classes
