### ISSUE TITLE
blocked-scoped-var

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#61]
http://eslint.org/docs/rules/block-scoped-var

This rule aims to reduce the usage of variables outside of their binding context

```
blocked-scoped-var: 2
```

e.g.
incorrect
```
function doIf() {
    if (true) {
        var build = true;
    }

    console.log(build);
}
```

correct
```
function doIf() {
    var build;

    if (true) {
        build = true;
    }

    console.log(build);
}
```

**Comment by nelsonic** [comment]
iDoubt anyone will _object_ to this rule. 👍

**Comment by jedwards1211** [comment]
If it's for ES2015, you might just want to go with `no-var`.  Though I don't think it can automatically turn off for code that's not `"env": { "es6": true }`
