### ISSUE TITLE
dot-notation

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#64]
http://eslint.org/docs/rules/dot-notation

```
dot-notation: 2
```

To keep consistency in the code we should only access properties of an object with the dot notation. However the allowPattern option allows us to define some specific cases where we can access property with brackets if the name of the property follow a specific pattern for example a name with underscore

```
data["foo_bar"] = 42; // no error in this case with allowPattern
```
We just need to decide which patterns are allowed

**Comment by jrans** [comment]
@SimonLab Unless you have decided on patterns I will put in with defaults and we can create a definitive list.
