### ISSUE TITLE
no-caller

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#66]
http://eslint.org/docs/rules/no-caller

```
no-caller: 2
```

using arguments.caller and arguments.callee add complexity and confusion we shouldn't use them

**Comment by eliascodes** [comment]
although this is an obsolete property now, I think

**Comment by nelsonic** [comment]
@eliascodes not yet "obsolete" but: 
> "deprecated in future versions of JavaScript and their use is forbidden in ECMAScript 5 while in strict mode" ... 

see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee#Why_was_arguments.callee_removed_from_ES5_strict_mode

This was a feature I _liked_ ... but not to fussed about it's removal. `¯\_(ツ)_/¯`
