### ISSUE TITLE
guard-for-in

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#67]
http://eslint.org/docs/rules/guard-for-in

```
guard-for-in: 0
```

We should use for - in but use Object.keys with foreach. This rule add more complexity so we are not going to use it

**Comment by eliascodes** [comment]
For the record, I think Simon's reasoning behind this is broadly along the following lines:
* We should always use `Object.keys` on objects we dont trust
* We should only use `for .. in` on objects we have created, so we are not surprised about looping over unexpected prototype attributes

**Comment by nelsonic** [comment]
@SimonLab && @eliascodes is there a _downside_ to _always_ using `Object.keys(obj).forEach ...` ?

**Comment by eliascodes** [comment]
@nelsonic other than having to type more characters, not that I can think of.

I found [this](http://jslint.com/help.html) btw:
> JSLint does not recommend use of the for in statement. Use Object.keys instead...
