### ISSUE TITLE
operator-linebreak

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#73]
http://eslint.org/docs/rules/operator-linebreak

`"before"` requires linebreaks to be placed before the operator

Personal preference, I think this 
```
var fullHeight = borderTop
  + innerHeight
  + borderBottom;
```
looks nicer than 

```
var fullHeight = borderTop +
  innerHeight +
  borderBottom;
```

The shape is more like a definition of a function or object.

p.s. i also prefer one step further with:
```
var fullHeight = borderTop
  + innerHeight
  + borderBottom
;
```

**Comment by nelsonic** [comment]
Hmm... OK! 👍
