### ISSUE TITLE
no-case-declarations

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#74]
http://eslint.org/docs/rules/no-case-declarations

It seems that wrapping your clauses in blocks retains the scope of where it was defined and not throughout the switch statement which can be quite useful

But it makes writing switch statements a little uglier.

I think though the better config option is:

```
no-case-declarations: 2
```

e.g.
incorrect:
```
switch (foo) {
    case 1:
        let x = 1;
        break;
    case 2:
        const y = 2;
        break;
    case 3:
        function f() {}
        break;
    default:
        class C {}
}
```

correct:
```
switch (foo) {
    case 1: {
        let x = 1;
        break;
    }
    case 2: {
        const y = 2;
        break;
    }
    case 3: {
        function f() {}
        break;
    }
    default: {
        class C {}
    }
}
```

**Comment by eliascodes** [comment]
The `let` / `const` examples aren't relevant if we're not using those keywords. How does this work with the `block-scoped-var` rule?
