### ISSUE TITLE
one-var

### ISSUE THREAD

**Issue by jrans** [dwyl/goodparts#78]
http://eslint.org/docs/rules/one-var

["error", { "initialized": "never", "uninitialized": "always" }]

defined variables should be given space and proper instantiation but undefined can be grouped together for brevity like so:

```
    var foo = true;
    var bar = false;
    var a, b, c;
```

**Comment by nelsonic** [comment]
@jrans how _often_ do you declare _uninitialized_ variables...? (_do you use more than one in a does-only-one-thing function_...?)

**Comment by jrans** [comment]
@nelsonic sometimes, but regardless,  if the case does arise having some style linting to handle it is better than none, this rule is not preventing the number of variable you declare just how the declaring should be done.

**Comment by nelsonic** [comment]
Sorry, my question _should_ have been: do we _want_ to _encourage_ people to have _multiple undeclared_ variables in functions? Having this as a _rule_ explicitly says that it's "_ok_" to have 
```js
var foo, bar, baz, global, do, crazy, things, etc;
```
When we _probably_ should be _limiting_ the use of _undeclared_ variables which are then set in a block within the function/script ... 
![image](https://cloud.githubusercontent.com/assets/194400/18757230/e0d45d44-80ea-11e6-8576-a26fd8bc98aa.png)

Although ... I suspect `no-unused-vars` https://github.com/dwyl/goodparts/issues/158 will address this to a _point_. I still _prefer_ to have variables declared one-per-line and in alphabetical order. #IKR! 😮
