### ISSUE TITLE
no-implicit-coercion

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#82]
http://eslint.org/docs/rules/no-implicit-coercion

```
no-implicit-coercion: 2
```

Use more explicit way to coerce to a specific type:

bad:
```
var b = !!foo;
var b = ~foo.indexOf(".");
var n = +foo;
var n = 1 * foo;
var s = "" + foo;
foo += "";
```

good:
```
var b = Boolean(foo);
var b = foo.indexOf(".") !== -1;
var n = Number(foo);
var n = Number(foo);
var s = String(foo);
foo = String(foo);
```

**Comment by eliascodes** [comment]
I agree that explicit conversions are clearer (esp. to beginners).

People often say implicit casting is/should be faster, but it seems like they are referring to poorly thought out benchmarks. It's often not a good idea to preempt or guess what optimizations the compiler is likely to perform.

**Comment by nelsonic** [comment]
Agreed. _way_ more `shoshin`
