### ISSUE TITLE
no-param-reassign

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#98]
http://eslint.org/docs/rules/no-param-reassign

```
no-param-reassign: [2, { "props": true }] 
```
This rule doesn't allow to change the parameter of a function event when the parameter is an object and the function try to change a property of this object. This will allow us to have immutable parameter. If we want to modify the parameter we need to create a new variable or object.

**Comment by jrans** [comment]
@SimonLab this seems sensible except `props` should be false. Consider:
```
function increment (x) {
  x.counter += 1;
} 

var x = { counter: 0 };

increment(x);
```
Essentially we still shouldn't disallow functions that mutate objects
